### ISSUE TITLE
Multi-lines literals

### ISSUE THREAD

**Issue by wismill** [mjansing/language-rdf#1]
Hi, according to the [Turtle specification](http://www.w3.org/TR/turtle/) (section 2.5.1 and 6.5: `STRING_LITERAL_LONG_QUOTE`), it is possible to use literals that span multiple lines when using triple quotes.

This package `language-rdf` does not support it yet.

**Comment by mjansing** [comment]
I merged PR #2 and published v0.3.0 of the package. Thank you and sorry for delay.
